### PR TITLE
Trying to fix the core/container module resolution

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by Ladicek** [comment]
Are those `module.xml` files needed? I believe we should inherit all of them from WildFly. If it's not working without them, then there's a problem somewhere else. Maybe in the fraction plugin?

**Comment by sberyozkin** [comment]
@Ladicek, I honestly don't know if it is possible to avoid adding them. Adding them one by one let me reach the current error message when trying to start the standalone-servers/web, otherwise it would fail with one of these modules not found. 
It was strange. First, for ex, I only added javax.api to module.conf, and then I got some other error eventually reaching that the 'jboss.logging' was missing and I could only fix it by adding module.xml and then I started getting missing 'javax.api' modules, etc again which led me to adding more module.xmls

**Comment by Ladicek** [comment]
Weird. WDYT about adding the usual WF14 comment to all of them, so that we can revisit later?

**Comment by sberyozkin** [comment]
I'm not sure yet these changes are sound or even needed at the container level :-)

**Comment by sberyozkin** [comment]
@Ladicek will I just close this PR ? I'm assuming that you will have your own PR coming in in time :-) ?

**Comment by Ladicek** [comment]
Good point. Agree, this should be closed.

**Pull request closed without merging**
