### PR TITLE
[THORN-2210] Initializing DeferredExtensionContext

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
Using the deprecated ExtensionRegistry constructor as it looks it is safer than trying to initialize the other one correctly

**Comment by Ladicek** [comment]
Just yesterday, I experienced a classloader barrier between `core/bootstrap` and `core/container`, so not sure if this works, but looks good on the first sight :-)

**Comment by sberyozkin** [comment]
@Ladicek, the container test itself involving the loading of DeferredExtensionContext passes, so I guess at least from the NPE protection point of view, it is safe. I'm not sure we have any case for the standalone xml extension to prove the new code really works :-)

**Comment by sberyozkin** [comment]
I've just updated it with the //WF14 as well

**Comment by Ladicek** [comment]
I'm not sure if we have a test for it, but I know we somehow support loading configuration from `standalone.xml`. I guess that's the most risky part.

**Pull request merged**
